replicaCount: 1
envVars:
  - name: REACT_APP_API_URI
    value: https://charles-api.continuousplatform.com

appname: charlescd-ui
  
image:
  name: zupcharles/charlescd-ui:latest
service:
  name: charlescd-ui-web
  type: ClusterIP
  ports:
   - name: http
     port: 3000
configmaps:
  enabled: false
startcommand: 
  enabled: false
ingress:
  enabled: false
resources:
   limits:
    cpu: 1
    memory: 1536Mi
   requests:
    cpu: 128m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
livenessProbe:
  enabled: true
  failureThreshold: 3
  httpGet:
    path: /
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 20
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 3000
    scheme: HTTP  
  initialDelaySeconds: 20
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 1   

istio:
  enabled: true