replicaCount: 1
image:
  repository: darwin-deploy
  tag: darwin-v-0-1-0-rc-1
  registry: realwavelab.azurecr.io

envVars:
  - name: CONSUL_HOST
    value: consul-server
  - name: DATABASE_HOST
    value: "postgresql"
  - name: DATABASE_PORT
    value: 5432
  - name: DATABASE_USER
    value: "postgres"
  - name: DATABASE_PASS
    value: "firstpassword"
  - name: DATABASE_NAME
    value: "charlesdeploy"
  - name: MOOVE_URL
    value: "http://charles-moove:8080"
  - name: DARWIN_NOTIFICATION_URL
    value: "http://charles-deploy.charles.svc.cluster.local:3000/notifications"
  - name: DARWIN_UNDEPLOYMENT_CALLBACK
    value: "http://charles-deploy.charles.svc.cluster.local:3000/notifications/undeployment"
  - name: DARWIN_DEPLOYMENT_CALLBACK
    value: "http://charles-deploy.charles.svc.cluster.local:3000/notifications/deployment"
  - name: SPINNAKER_URL
    value: "https://darwin-spinnaker-gate.continuousplatform.com"
  - name: SPINNAKER_GITHUB_ACCOUNT
    value: "github-artifact"

secretEnvVars:
  - name: ENCRYPTION_KEY
    secretName: "deploy-aes256-key"
    secretKey: "encryption-key"

appname: charles-deploy

service:
  name: charles-deploy
  type: ClusterIP
  ports:
   - name: http
     port: 3000
configmaps:
  enabled: false
startcommand: 
  enabled: false
ingress:
  enabled: false
resources:
   limits:
    cpu: 512m
    memory: 1024Mi
   requests:
    cpu: 128m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
livenessProbe:
  enabled: true
  failureThreshold: 3
  httpGet:
    path: /healthcheck
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /healthcheck
    port: 3000
    scheme: HTTP  
  initialDelaySeconds: 30
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 1   

istio:
  enabled: true

initContainer:
  enabled: true
  name: postgres-check
  image: postgres:alpine
  command: "['sh', '-c',  'until pg_isready -U postgres -h postgresql; do echo notReady; sleep 2;done']"