coverage:
  status:
    patch:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto 
        # advanced
        branches: 
          - master
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
      villager:
        target: 30%
        flags:
          - villager
      circlematcher:
        target: 70%
        flags:
          - circlematcher
      octopipe:
        target: 30%
        flags:
          - octopipe
      moove:
        target: 50%
        flags:
          - moove
      butler:
        target: 70%
        flags:
          - butler
      ui:
        target: 30%
        flags:
          - ui
      
flags:
  villager:
    paths:
      - villager/src/main/java/
    carryforward: true
  circlematcher:
    paths:
      - circle-matcher/src/main/java/
    carryforward: true
  octopipe:
    paths:
      - octopipe/
    carryforward: true
  moove:
    paths:
      - moove/
    carryforward: true
  butler:
    paths:
      - butler/
    carryforward: true
  ui:
    paths:
      - ui/
    carryforward: true

ignore:
  - ".github/**/*"