replicaCount: 1

envVars:
  - name: SPRING_PROFILES_ACTIVE
    value: k8s
  - name: DARWIN_VILLAGER_DB_URI
    value: jdbc:postgresql://postgresql:5432/charlesvillager
  - name: DARWIN_VILLAGER_DB_USERNAME
    value: postgres
  - name: DARWIN_VILLAGER_DB_PASSWORD
    value: firstpassword
  - name: DARWIN_BUILD_TIMEOUT
    value: 15
  - name: DARWIN_MOOVE_ORGANIZATION
    value: zup
  - name: CRYPT_KEY
    value: pvMPbPPNNB

appname: charles-villager

image:
  repository: darwin-villager
  tag: darwin-v-0-1-0-rc-1
  registry: realwavelab.azurecr.io
service:
  name: charles-villager
  type: ClusterIP
  ports:
   - name: http
     port: 8080
configmaps:
  enabled: false
startcommand:
  enabled: false
ingress:
  enabled: false
resources:
   limits:
    cpu: 512m
    memory: 1024Mi
   requests:
    cpu: 128m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
livenessProbe:
  enabled: true
  failureThreshold: 3
  httpGet:
    path: /health
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 20
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /health
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 20
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 1

istio:
  enabled: true

initContainer:
  enabled: true
  name: postgres-check
  image: postgres:alpine
  command: "['sh', '-c', 'until pg_isready -U postgres -h postgresql; do echo notReady; sleep 2;done']"
