replicaCount: 1
envVars:
  - name: REACT_APP_API_URI
    value: ""


appname: charles-ui-new
  
image:
  repository: darwin-ui-new
  tag: darwin-empty-basepath
  registry: realwavelab.azurecr.io
service:
  name: charles-ui-new-web
  type: ClusterIP
  ports:
   - name: http
     port: 3000
configmaps:
  enabled: false
startcommand: 
  enabled: false
ingress:
  enabled: false
resources:
   limits:
    cpu: 512m
    memory: 1024Mi
   requests:
    cpu: 128m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
livenessProbe:
  enabled: true
  failureThreshold: 3
  httpGet:
    path: /
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 20
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 3000
    scheme: HTTP  
  initialDelaySeconds: 20
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 1   

istio:
  enabled: true

initContainer:
  enabled: false
