replicaCount: 1
envVars:
  - name: HOST
    value: /moove
  - name: NOTIFICATION
    value: /notifications
  - name: KEYCLOAK
    value: /keycloak
  - name: CIRCLE_MATCHER
    value: /darwin-circle-matcher

appname: charles-ui-legacy
  
image:
  repository: darwin-ui-legacy
  tag: darwin-hostname-cookie
  registry: realwavelab.azurecr.io
service:
  name: charles-ui-legacy-web
  type: ClusterIP
  ports:
   - name: http
     port: 3000
configmaps:
  enabled: false
startcommand: 
  enabled: false
ingress:
  enabled: false
resources:
   limits:
    cpu: 512m
    memory: 1024Mi
   requests:
    cpu: 128m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
livenessProbe:
  enabled: true
  failureThreshold: 3
  httpGet:
    path: /
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 20
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 3000
    scheme: HTTP  
  initialDelaySeconds: 20
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 1   

istio:
  enabled: true

initContainer:
  enabled: false