replicaCount: 1
envVars:
  - name: SPRING_PROFILES_ACTIVE
    value: "k8s"
  - name: DB_URL
    value: "jdbc:postgresql://charlescd-postgresql:5432/charlescd_moove"
  - name: DB_USERNAME
    value: "charlescd_moove"
  - name: DB_PASSWORD
    value: "7Qs2KuM9gYzw48BS"
  - name: KEYCLOCK_REALM
    value: "charlescd"
  - name: KEYCLOAK_SERVER_URL
    value: "http://charlescd-keycloak-http/auth"
  - name: KEYCLOAK_CLIENT_ID
    value: "realm-charlescd"
  - name: KEYCLOAK_CLIENT_SECRET
    value: "f2dc9337-9aaf-461f-9c7f-d02a0439ae4d"
  - name: ORIGIN_HOSTS
    value: "http://localhost:3000,http://localhost:3001,http://localhost:8081,http://localhost:8080"

secretEnvVars:
  - name: ENCRYPTION_KEY
    secretName: "application-aes256-key"
    secretKey: "encryption-key"

appname: charlescd-moove
    
image:
  name: zupcharles/charlescd-moove:latest
service:
  name: charlescd-moove
  type: ClusterIP
  ports:
   - name: http
     port: 8080
configmaps:
  enabled: false
startcommand: 
  enabled: false
ingress:
  enabled: false
resources:
   limits:
    cpu: 1
    memory: 1536Mi
   requests:
    cpu: 128m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
livenessProbe:
  enabled: true
  failureThreshold: 3
  httpGet:
    path: /actuator/health
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 120
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /actuator/health
    port: 8080
    scheme: HTTP  
  initialDelaySeconds: 120
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 1   

istio:
  enabled: true